# App name
spring.application.name=QuotationGenerator

# Server port (Render sets PORT automatically, default to 8080 for local run)
server.port=${PORT:8080}

# MongoDB connection (pick from Render env variable MONGO_URL)
spring.data.mongodb.uri=${MONGO_URL}

# Database name (important for MongoDB Atlas!)
spring.data.mongodb.database=MedicalDB

# Thymeleaf template location
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.cache=false

# Logging
logging.level.org.springframework=INFO
logging.level.com.nt=DEBUG  

# Enable devtools restart & live reload (only useful locally)
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true
