# App name
spring.application.name=QuotationGenerator

# Server port (Railway sets PORT automatically)
server.port=${PORT:8080}

# MongoDB connection using Railway env variables
spring.data.mongodb.uri=${MONGO_URL}

# JSP View Resolver
spring.mvc.view.prefix=/WEB-INF/pages/
spring.mvc.view.suffix=.jsp

# Logging
logging.level.org.springframework=INFO
logging.level.com.yourpackage=DEBUG
